---
- name: Add Bird2 apt key
  ansible.builtin.get_url:
    url: "{{ app_bgp_bird2_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/bird2.asc
    mode: '0644'
    force: true

- name: Add Bird2 repository
  apt_repository:
    repo: "{{ app_bgp_bird2_apt_repository }}"
    state: present
    update_cache: true

- name: Install Bird2
  ansible.builtin.package:
    name: "bird2"
    state: latest
