---
# - name: Add Bird2 apt key
#   ansible.builtin.apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: B188E2B695BD4743

# - name: Add Bird2 repository
#   apt_repository:
#     repo: "{{ app_bgp_bird2_apt_repository }}"
#     state: present
#     update_cache: true

# - name: Install Bird2
#   ansible.builtin.package:
#     name: "bird2"
#     state: latest

# Temporary solution as no deb package available
# https://gitlab.nic.cz/labs/bird/-/pipelines?page=1&scope=all&ref=v2.13.1
- name: Copy package
  ansible.builtin.copy:
    src: "bird2_2.13.1.1687446515.52bae235-cznic.1_amd64.deb"
    dest: "~/bird2_2.13.1.1687446515.52bae235-cznic.1_amd64.deb"

- name: Install Bird2
  ansible.builtin.apt:
    deb: ~/bird2_2.13.1.1687446515.52bae235-cznic.1_amd64.deb

- name: Create bird.log file
  ansible.builtin.file:
    dest: /var/log/bird.log
    state: touch
    owner: bird
    group: bird
    mode: 0644
    modification_time: preserve
    access_time: preserve
