---
- name: Install Bird prometheus exporter
  ansible.builtin.package:
    name: "prometheus-bird-exporter"
    state: latest

- name: Configure Bird prometheus exporter
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-bird-exporter
    regexp: "^ARGS"
    line: 'ARGS="-format.new -bird.v2"'
    state: present
  notify: restart bird_exporter
